# Build clusterregistry container using Google Cloud Container Builder
# and push it the Google Container Registry.
#
# The image can be built automatically for every change on the code using
# https://cloud.google.com/container-builder/docs/how-to/build-triggers
#
# See GCB_build.md file for instructions.
timeout: 10800s

steps:
# Build and tag clusterregistry image. Image will be tag as 'latest'
- name: 'gcr.io/cloud-builders/bazel'
  args: ['build', '//cmd/clusterregistry:clusterregistry-image.tar']

- name: 'gcr.io/cloud-builders/docker'
  args: ['load', '-i', 'bazel-bin/cmd/clusterregistry/clusterregistry-image.tar']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'bazel/cmd/clusterregistry:clusterregistry-image', 'gcr.io/google_containers/${_PREFIX}clusterregistry:${_VERSION}']

# Build and release to Cloud Storage the command-line tool
- name: 'gcr.io/cloud-builders/bazel'
  args: ['build', '//cmd/crinit']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'bazel-bin/cmd/crinit/crinit', 'gs://kubernetes-release/addons/${_PREFIX}crinit/${_VERSION}/']

# Push image to registry
images: ['gcr.io/google_containers/${_PREFIX}clusterregistry:${_VERSION}']
